server:
  port: 8888
spring:
  application:
    name: Spiring-Boot-WebSocket-Service

#添加Thymeleaf配置
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html